const countries = [
  { name: "Algeria", dial_code: "+213", flag: "🇩🇿" },
  { name: "Angola", dial_code: "+244", flag: "🇦🇴" },
  { name: "Benin", dial_code: "+229", flag: "🇧🇯" },
  { name: "Botswana", dial_code: "+267", flag: "🇧🇼" },
  { name: "Burkina Faso", dial_code: "+226", flag: "🇧🇫" },
  { name: "Burundi", dial_code: "+257", flag: "🇧🇮" },
  { name: "Cabo Verde", dial_code: "+238", flag: "🇨🇻" },
  { name: "Cameroon", dial_code: "+237", flag: "🇨🇲" },
  { name: "Central African Republic", dial_code: "+236", flag: "🇨🇫" },
  { name: "Chad", dial_code: "+235", flag: "🇹🇩" },
  { name: "Comoros", dial_code: "+269", flag: "🇰🇲" },
  { name: "Congo (Republic)", dial_code: "+242", flag: "🇨🇬" },
  { name: "Congo (DRC)", dial_code: "+243", flag: "🇨🇩" },
  { name: "Djibouti", dial_code: "+253", flag: "🇩🇯" },
  { name: "Egypt", dial_code: "+20", flag: "🇪🇬" },
  { name: "Equatorial Guinea", dial_code: "+240", flag: "🇬🇶" },
  { name: "Eritrea", dial_code: "+291", flag: "🇪🇷" },
  { name: "Eswatini", dial_code: "+268", flag: "🇸🇿" },
  { name: "Ethiopia", dial_code: "+251", flag: "🇪🇹" },
  { name: "Gabon", dial_code: "+241", flag: "🇬🇦" },
  { name: "Gambia", dial_code: "+220", flag: "🇬🇲" },
  { name: "Ghana", dial_code: "+233", flag: "🇬🇭" },
  { name: "Guinea", dial_code: "+224", flag: "🇬🇳" },
  { name: "Guinea-Bissau", dial_code: "+245", flag: "🇬🇼" },
  { name: "Ivory Coast", dial_code: "+225", flag: "🇨🇮" },
  { name: "Kenya", dial_code: "+254", flag: "🇰🇪" },
  { name: "Lesotho", dial_code: "+266", flag: "🇱🇸" },
  { name: "Liberia", dial_code: "+231", flag: "🇱🇷" },
  { name: "Libya", dial_code: "+218", flag: "🇱🇾" },
  { name: "Madagascar", dial_code: "+261", flag: "🇲🇬" },
  { name: "Malawi", dial_code: "+265", flag: "🇲🇼" },
  { name: "Mali", dial_code: "+223", flag: "🇲🇱" },
  { name: "Mauritania", dial_code: "+222", flag: "🇲🇷" },
  { name: "Mauritius", dial_code: "+230", flag: "🇲🇺" },
  { name: "Morocco", dial_code: "+212", flag: "🇲🇦" },
  { name: "Mozambique", dial_code: "+258", flag: "🇲🇿" },
  { name: "Namibia", dial_code: "+264", flag: "🇳🇦" },
  { name: "Niger", dial_code: "+227", flag: "🇳🇪" },
  { name: "Nigeria", dial_code: "+234", flag: "🇳🇬" },
  { name: "Rwanda", dial_code: "+250", flag: "🇷🇼" },
  { name: "São Tomé and Príncipe", dial_code: "+239", flag: "🇸🇹" },
  { name: "Senegal", dial_code: "+221", flag: "🇸🇳" },
  { name: "Seychelles", dial_code: "+248", flag: "🇸🇨" },
  { name: "Sierra Leone", dial_code: "+232", flag: "🇸🇱" },
  { name: "Somalia", dial_code: "+252", flag: "🇸🇴" },
  { name: "South Africa", dial_code: "+27", flag: "🇿🇦" },
  { name: "South Sudan", dial_code: "+211", flag: "🇸🇸" },
  { name: "Sudan", dial_code: "+249", flag: "🇸🇩" },
  { name: "Tanzania", dial_code: "+255", flag: "🇹🇿" },
  { name: "Togo", dial_code: "+228", flag: "🇹🇬" },
  { name: "Tunisia", dial_code: "+216", flag: "🇹🇳" },
  { name: "Uganda", dial_code: "+256", flag: "🇺🇬" },
  { name: "Zambia", dial_code: "+260", flag: "🇿🇲" },
  { name: "Zimbabwe", dial_code: "+263", flag: "🇿🇼" }
];
